version: '1.0'
repository:
  name: 'content-analysis-agent'
  description: 'Content Analysis Agent with DurableAgent capabilities'

agents:
- name: ContentAnalyzer
  type: durable_agent
  service_name: content-analyzer
  main_file: services/content-analyzer/app.py
  port: 8005
  has_tools: true
  dockerfile_path: services/content-analyzer/Dockerfile
  
  detection:
    pattern: "custom_class"
    class_name: "ContentAnalysisAgent"
    instance_name: "content_agent"
    instantiation_pattern: "ContentAnalysisAgent("

build:
  python_version: '3.11'
  base_image: python:3.11-slim
  global_dependencies:
    - dapr-agents>=0.8.1
    - starlette==0.47.2
    - python-dotenv>=1.0.0
    - fastapi
    - uvicorn
    - pydantic
  context: .
  registry:
    host: localhost
    port: '5000'
    insecure: true
